language: python
env:
- DJANGO_VERSION='>=2.2,<2.3'
- DJANGO_VERSION='>=3.0,<3.1'
- DJANGO_VERSION='>=3.1,<3.2'
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
install:
- pip install Django$DJANGO_VERSION
- pip install -r requirements.txt
script:
- python setup.py test

jobs:
  exclude:
  - python: '3.5'
    env: DJANGO_VERSION='>=3.0,<3.1'
  - python: '3.5'
    env: DJANGO_VERSION='>=3.1,<3.2'
  include:
    - stage: deploy
      script: skip
      python: '3.6'
      deploy: &pypi
        provider: pypi
        user: matwey
        password:
          secure: "KR+BglUiEjxkh9SEI0En/JMUlXSA8njRAutKuSHylV2C/z9wJcfKiwqdYXE7XKt+nDSsHTHHNlGIRPZceA71/SB8loXcvihsP6Bu+xhTKbvTF6VZ4gFd+t5fWn8pTB1S5B80tlFvVGEC/JJGczL6mbd2xf9ohSVV5C/BH/AbHwNwl0lOCXYr4dvdaqLK4cnzGz477HF9okyrJ4uruYg77jinWLAtXbsWe7Io7hpSmQewLel4sPsNi+Axlf9XBsTu6cme6kb9ypdZlmdXhn6y54VoW6a1TU7v9dYrmM2sIezmLiP3iRsFsvCYp1QCX2gpi0eDgOHi4EMGxKnI5PfH0FUElLweH+RIPaCtHtWR+5qwcwJdITocl29hRMxXAHPphi5tzENUZLEfGuMmDIBP8fzWqLBtxjqRBjY4GkzjjWtGJyWVL/ebOyxVoC5BEtbvJ7JQLLLHKgZfsK4cqhCcQ5lHXrah+lcRELZToy8m/eD00rCHjSUYCDzqlKatEGEu224uHgzW2S0WCJnj2UEPPJ5+2ntmLoYKRD0XhBHSObcKSW+SuVk/rQPHyjoQLidzIL7wvU/8+8gNCzofjDjIzW8bqsv6QcJhuie83oqnkP1wK+DK6T2qM37S0Ppgln2UjMH3NX2Yxb4/kpW92UZy7bdLRmJWXLmnMkPSPLJGDe4="
        skip_existing: true
        distributions: sdist bdist_wheel
        on:
          tags: true
